
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async fetchPob(refresh: boolean) : Promise<Result<GoogleDriveFileInfo, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_pob", { refresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installedPobInfo() : Promise<Result<PobVersion | null, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("installed_pob_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installPob(fileData: GoogleDriveFileInfo | null) : Promise<Result<boolean, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_pob", { fileData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelInstallPob() : Promise<Result<null, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_install_pob") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseVersion(fileName: string) : Promise<Result<string, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_version", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uninstallPob() : Promise<Result<null, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_pob") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executePob() : Promise<Result<null, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_pob") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstallPath() : Promise<Result<string, ErrorKind>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_install_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
installProgress: InstallProgress
}>({
installProgress: "install-progress"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * IPC error type for frontend consumption.
 * Designed for UI-actionable categories, not implementation details.
 */
export type ErrorKind = 
/**
 * User cancelled the operation (not an error, no toast needed)
 */
{ kind: "cancelled" } | 
/**
 * Network/connectivity issues (retry may help)
 */
{ kind: "network"; message: string } | 
/**
 * Filesystem/permission issues
 */
{ kind: "io"; message: string } | 
/**
 * Resource not found (e.g., file not on Google Drive)
 */
{ kind: "notFound"; message: string } | 
/**
 * Conflict state (e.g., PoB is running)
 */
{ kind: "conflict"; message: string } | 
/**
 * Other domain errors
 */
{ kind: "domain"; message: string }
export type GoogleDriveFileInfo = { id: string; name: string; isFolder: boolean }
export type InstallPhase = "downloading" | "extracting" | "backingUp" | "moving" | "restoring" | "finalizing" | "uninstalling" | "preparing"
export type InstallProgress = ({ status: "started"; total_size?: number | null } | { status: "inProgress"; percent: number } | { status: "completed" } | { status: "failed"; reason: string } | { status: "cancelled" }) & { taskId: string; phase: InstallPhase }
export type PobVersion = { version: string; installedAt: string; fileId: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
